module.exports = [
  {
    id: 1,
    fullName: 'Candidate',
    regNo: 'POL/NGN/001',
    programType: 'INTERMIDIATE',
  },
  {
    id: 2,
    fullName: 'Candidate',
    regNo: 'POL/NGN/002',
    programType: 'INTERMIDIATE',
  },
  {
    id: 3,
    fullName: 'Candidate',
    regNo: 'POL/NGN/003',
    programType: 'INTERMIDIATE',
  },
  {
    id: 4,
    fullName: 'Candidate',
    regNo: 'POL/NGN/004',
    programType: 'INTERMIDIATE',
  },
  {
    id: 5,
    fullName: 'Candidate',
    regNo: 'POL/NGN/005',
    programType: 'INTERMIDIATE',
  },
  {
    id: 6,
    fullName: 'Candidate',
    regNo: 'POL/NGN/006',
    programType: 'INTERMIDIATE',
  },
  {
    id: 7,
    fullName: 'Candidate',
    regNo: 'POL/NGN/007',
    programType: 'INTERMIDIATE',
  },
  {
    id: 8,
    fullName: 'Candidate',
    regNo: 'POL/NGN/008',
    programType: 'INTERMIDIATE',
  },
  {
    id: 9,
    fullName: 'Candidate',
    regNo: 'POL/NGN/009',
    programType: 'INTERMIDIATE',
  },
  {
    id: 10,
    fullName: 'Candidate',
    regNo: 'POL/NGN/010',
    programType: 'INTERMIDIATE',
  },
  {
    id: 11,
    fullName: 'Candidate',
    regNo: 'POL/NGN/011',
    programType: 'INTERMIDIATE',
  },
  {
    id: 12,
    fullName: 'Candidate',
    regNo: 'POL/NGN/012',
    programType: 'INTERMIDIATE',
  },
  {
    id: 13,
    fullName: 'Candidate',
    regNo: 'POL/NGN/013',
    programType: 'INTERMIDIATE',
  },
  {
    id: 14,
    fullName: 'Candidate',
    regNo: 'POL/NGN/014',
    programType: 'INTERMIDIATE',
  },
  {
    id: 15,
    fullName: 'Candidate',
    regNo: 'POL/NGN/015',
    programType: 'INTERMIDIATE',
  },
  {
    id: 16,
    fullName: 'Candidate',
    regNo: 'POL/NGN/016',
    programType: 'INTERMIDIATE',
  },
  {
    id: 17,
    fullName: 'Candidate',
    regNo: 'POL/NGN/017',
    programType: 'INTERMIDIATE',
  },
  {
    id: 18,
    fullName: 'Candidate',
    regNo: 'POL/NGN/018',
    programType: 'INTERMIDIATE',
  },
  {
    id: 19,
    fullName: 'Candidate',
    regNo: 'POL/NGN/019',
    programType: 'INTERMIDIATE',
  },
  {
    id: 20,
    fullName: 'Candidate',
    regNo: 'POL/NGN/020',
    programType: 'INTERMIDIATE',
  },
  {
    id: 21,
    fullName: 'Candidate',
    regNo: 'POL/NGN/021',
    programType: 'INTERMIDIATE',
  },
  {
    id: 22,
    fullName: 'Candidate',
    regNo: 'POL/NGN/022',
    programType: 'INTERMIDIATE',
  },
  {
    id: 23,
    fullName: 'Candidate',
    regNo: 'POL/NGN/023',
    programType: 'INTERMIDIATE',
  },
  {
    id: 24,
    fullName: 'Candidate',
    regNo: 'POL/NGN/024',
    programType: 'INTERMIDIATE',
  },
  {
    id: 25,
    fullName: 'Candidate',
    regNo: 'POL/NGN/25',
    programType: 'INTERMIDIATE',
  },
  {
    id: 26,
    fullName: 'Candidate',
    regNo: 'POL/NGN/026',
    programType: 'INTERMIDIATE',
  },
  {
    id: 27,
    fullName: 'Candidate',
    regNo: 'POL/NGN/027',
    programType: 'INTERMIDIATE',
  },
  {
    id: 28,
    fullName: 'Candidate',
    regNo: 'POL/NGN/028',
    programType: 'INTERMIDIATE',
  },
  {
    id: 29,
    fullName: 'Candidate',
    regNo: 'POL/NGN/029',
    programType: 'INTERMIDIATE',
  },
  {
    id: 30,
    fullName: 'Candidate',
    regNo: 'POL/NGN/030',
    programType: 'INTERMIDIATE',
  },
  {
    id: 31,
    fullName: 'Candidate',
    regNo: 'POL/NGN/031',
    programType: 'INTERMIDIATE',
  },
  {
    id: 32,
    fullName: 'Candidate',
    regNo: 'POL/NGN/032',
    programType: 'INTERMIDIATE',
  },
  {
    id: 33,
    fullName: 'Candidate',
    regNo: 'POL/NGN/033',
    programType: 'INTERMIDIATE',
  },
  {
    id: 34,
    fullName: 'Candidate',
    regNo: 'POL/NGN/034',
    programType: 'INTERMIDIATE',
  },
  {
    id: 35,
    fullName: 'Candidate',
    regNo: 'POL/NGN/035',
    programType: 'INTERMIDIATE',
  },
  {
    id: 36,
    fullName: 'Candidate',
    regNo: 'POL/NGN/036',
    programType: 'INTERMIDIATE',
  },
  {
    id: 37,
    fullName: 'Candidate',
    regNo: 'POL/NGN/037',
    programType: 'INTERMIDIATE',
  },
  {
    id: 38,
    fullName: 'Candidate',
    regNo: 'POL/NGN/038',
    programType: 'INTERMIDIATE',
  },
  {
    id: 39,
    fullName: 'Candidate',
    regNo: 'POL/NGN/039',
    programType: 'INTERMIDIATE',
  },
  {
    id: 40,
    fullName: 'Candidate',
    regNo: 'POL/NGN/040',
    programType: 'INTERMIDIATE',
  },
  {
    id: 41,
    fullName: 'Candidate',
    regNo: 'POL/NGN/041',
    programType: 'INTERMIDIATE',
  },
  {
    id: 42,
    fullName: 'Candidate',
    regNo: 'POL/NGN/042',
    programType: 'INTERMIDIATE',
  },
  {
    id: 43,
    fullName: 'Candidate',
    regNo: 'POL/NGN/043',
    programType: 'INTERMIDIATE',
  },
  {
    id: 44,
    fullName: 'Candidate',
    regNo: 'POL/NGN/044',
    programType: 'INTERMIDIATE',
  },
  {
    id: 45,
    fullName: 'Candidate',
    regNo: 'POL/NGN/045',
    programType: 'INTERMIDIATE',
  },
  {
    id: 46,
    fullName: 'Candidate',
    regNo: 'POL/NGN/046',
    programType: 'INTERMIDIATE',
  },
  {
    id: 47,
    fullName: 'Candidate',
    regNo: 'POL/NGN/047',
    programType: 'INTERMIDIATE',
  },
  {
    id: 48,
    fullName: 'Candidate',
    regNo: 'POL/NGN/048',
    programType: 'INTERMIDIATE',
  },
  {
    id: 49,
    fullName: 'Candidate',
    regNo: 'POL/NGN/049',
    programType: 'INTERMIDIATE',
  },
  {
    id: 50,
    fullName: 'Candidate',
    regNo: 'POL/NGN/050',
    programType: 'INTERMIDIATE',
  },
  {
    id: 51,
    fullName: 'Candidate',
    regNo: 'POL/NGN/051',
    programType: 'INTERMIDIATE',
  },
  {
    id: 52,
    fullName: 'Candidate',
    regNo: 'POL/NGN/052',
    programType: 'INTERMIDIATE',
  },
  {
    id: 53,
    fullName: 'Candidate',
    regNo: 'POL/NGN/053',
    programType: 'INTERMIDIATE',
  },
  {
    id: 54,
    fullName: 'Candidate',
    regNo: 'POL/NGN/054',
    programType: 'INTERMIDIATE',
  },
  {
    id: 55,
    fullName: 'Candidate',
    regNo: 'POL/NGN/055',
    programType: 'INTERMIDIATE',
  },
  {
    id: 56,
    fullName: 'Candidate',
    regNo: 'POL/NGN/056',
    programType: 'INTERMIDIATE',
  },
  {
    id: 57,
    fullName: 'Candidate',
    regNo: 'POL/NGN/057',
    programType: 'INTERMIDIATE',
  },
  {
    id: 58,
    fullName: 'Candidate',
    regNo: 'POL/NGN/058',
    programType: 'INTERMIDIATE',
  },
  {
    id: 59,
    fullName: 'Candidate',
    regNo: 'POL/NGN/059',
    programType: 'INTERMIDIATE',
  },
  {
    id: 60,
    fullName: 'Candidate',
    regNo: 'POL/NGN/060',
    programType: 'INTERMIDIATE',
  },
  {
    id: 61,
    fullName: 'Candidate',
    regNo: 'POL/NGN/061',
    programType: 'INTERMIDIATE',
  },
  {
    id: 62,
    fullName: 'Candidate',
    regNo: 'POL/NGN/062',
    programType: 'INTERMIDIATE',
  },
  {
    id: 63,
    fullName: 'Candidate',
    regNo: 'POL/NGN/063',
    programType: 'INTERMIDIATE',
  },
  {
    id: 64,
    fullName: 'Candidate',
    regNo: 'POL/NGN/064',
    programType: 'INTERMIDIATE',
  },
  {
    id: 65,
    fullName: 'Candidate',
    regNo: 'POL/NGN/065',
    programType: 'INTERMIDIATE',
  },
  {
    id: 66,
    fullName: 'Candidate',
    regNo: 'POL/NGN/066',
    programType: 'INTERMIDIATE',
  },
  {
    id: 67,
    fullName: 'Candidate',
    regNo: 'POL/NGN/067',
    programType: 'INTERMIDIATE',
  },
  {
    id: 68,
    fullName: 'Candidate',
    regNo: 'POL/NGN/068',
    programType: 'INTERMIDIATE',
  },
  {
    id: 69,
    fullName: 'Candidate',
    regNo: 'POL/NGN/069',
    programType: 'INTERMIDIATE',
  },
  {
    id: 70,
    fullName: 'Candidate',
    regNo: 'POL/NGN/070',
    programType: 'INTERMIDIATE',
  },
  {
    id: 71,
    fullName: 'Candidate',
    regNo: 'POL/NGN/071',
    programType: 'INTERMIDIATE',
  },
  {
    id: 72,
    fullName: 'Candidate',
    regNo: 'POL/NGN/072',
    programType: 'INTERMIDIATE',
  },
  {
    id: 73,
    fullName: 'Candidate',
    regNo: 'POL/NGN/73',
    programType: 'INTERMIDIATE',
  },
  {
    id: 74,
    fullName: 'Candidate',
    regNo: 'POL/NGN/074',
    programType: 'INTERMIDIATE',
  },
  {
    id: 75,
    fullName: 'Candidate',
    regNo: 'POL/NGN/075',
    programType: 'INTERMIDIATE',
  },
  {
    id: 76,
    fullName: 'Candidate',
    regNo: 'POL/NGN/076',
    programType: 'INTERMIDIATE',
  },
  {
    id: 77,
    fullName: 'Candidate',
    regNo: 'POL/NGN/077',
    programType: 'INTERMIDIATE',
  },
  {
    id: 78,
    fullName: 'Candidate',
    regNo: 'POL/NGN/078',
    programType: 'INTERMIDIATE',
  },
  {
    id: 79,
    fullName: 'Candidate',
    regNo: 'POL/NGN/079',
    programType: 'INTERMIDIATE',
  },
  {
    id: 80,
    fullName: 'Candidate',
    regNo: 'POL/NGN/080',
    programType: 'INTERMIDIATE',
  },
  {
    id: 81,
    fullName: 'Candidate',
    regNo: 'POL/NGN/081',
    programType: 'INTERMIDIATE',
  },
  {
    id: 82,
    fullName: 'Candidate',
    regNo: 'POL/NGN/082',
    programType: 'INTERMIDIATE',
  },
  {
    id: 83,
    fullName: 'Candidate',
    regNo: 'POL/NGN/083',
    programType: 'INTERMIDIATE',
  },
  {
    id: 84,
    fullName: 'Candidate',
    regNo: 'POL/NGN/084',
    programType: 'INTERMIDIATE',
  },
  {
    id: 85,
    fullName: 'Candidate',
    regNo: 'POL/NGN/085',
    programType: 'INTERMIDIATE',
  },
  {
    id: 86,
    fullName: 'Candidate',
    regNo: 'POL/NGN/086',
    programType: 'INTERMIDIATE',
  },
  {
    id: 87,
    fullName: 'Candidate',
    regNo: 'POL/NGN/087',
    programType: 'INTERMIDIATE',
  },
  {
    id: 88,
    fullName: 'Candidate',
    regNo: 'POL/NGN/088',
    programType: 'INTERMIDIATE',
  },
  {
    id: 89,
    fullName: 'Candidate',
    regNo: 'POL/NGN/089',
    programType: 'INTERMIDIATE',
  },
  {
    id: 90,
    fullName: 'Candidate',
    regNo: 'POL/NGN/090',
    programType: 'INTERMIDIATE',
  },
  {
    id: 91,
    fullName: 'Candidate',
    regNo: 'POL/NGN/091',
    programType: 'INTERMIDIATE',
  },
  {
    id: 92,
    fullName: 'Candidate',
    regNo: 'POL/NGN/092',
    programType: 'INTERMIDIATE',
  },
  {
    id: 93,
    fullName: 'Candidate',
    regNo: 'POL/NGN/093',
    programType: 'INTERMIDIATE',
  },
  {
    id: 94,
    fullName: 'Candidate',
    regNo: 'POL/NGN/094',
    programType: 'INTERMIDIATE',
  },
  {
    id: 95,
    fullName: 'Candidate',
    regNo: 'POL/NGN/095',
    programType: 'INTERMIDIATE',
  },
  {
    id: 96,
    fullName: 'Candidate',
    regNo: 'POL/NGN/096',
    programType: 'INTERMIDIATE',
  },
  {
    id: 97,
    fullName: 'Candidate',
    regNo: 'POL/NGN/097',
    programType: 'INTERMIDIATE',
  },
  {
    id: 98,
    fullName: 'Candidate',
    regNo: 'POL/NGN/098',
    programType: 'INTERMIDIATE',
  },
  {
    id: 99,
    fullName: 'Candidate',
    regNo: 'POL/NGN/099',
    programType: 'INTERMIDIATE',
  },
  {
    id: 100,
    fullName: 'Candidate',
    regNo: 'POL/NGN/100',
    programType: 'INTERMIDIATE',
  },
]
